### ISSUE TITLE
This application violates the GNU license!

### ISSUE THREAD

**Issue by ikanakova** [Arturo254/RiMusic#3]
Immediately state in the readme that this is a fork!

And delete the lie: Dev By Arturo Cervantes 亗

**Comment by Arturo254** [comment]
I never said I was the lead developer on the README.MD.
I just put "Dev by Arturo".
As for the fork, I forgot to put it in.

Thanks for your comment

**Comment by ikanakova** [comment]
> As for the fork, I forgot to put it in.

What about InnerTune and others? Did you forget that they are all forks as well?

**Comment by Arturo254** [comment]
el código de la aplicación tiene 2 años sin actualización y la aplicación ya no funciona
Y el código como tal esta escrito en Java

Yo reescribi el código a Kotlin (Usando Flutter y JetPack Compose) además lo actualize para la versión de Material You 3 (de android 11+)

Si gustas puedes consultar el código 👍
